### ISSUE TITLE
Investigate possibility to replace package.json with .something 

### ISSUE THREAD

**Issue by soichih** [soichih/sca-wf#22]
I believe I can/should lessen burden for app developer by allowing them to define .<something> file similar to .travis.yml and use resource defined hooks shared by all application enabled on that resource.

This approach allows much less shell scripting and also capability for resource admin to decide how each application will be executed (pbs, condor, vm, etc..)

**Comment by soichih** [comment]
Note to myself..

We need to allow apps to run on multiple resources. 

```
karst:
    maxtime: 12:00:00
    cores: 8
    cmd: ./run.sh
  
singularity:
    container: brainlife/life
   
```
